@startuml use-case-diagram
left to right direction

actor "Buyer" #black;line.bold;

actor "Seller" #red;line.bold;



rectangle Swapp {
  usecase "Login" as UC1
  usecase "Make a profile" as UC2
  usecase "Search" as UC3
  usecase "Make ad posts" as UC4
  usecase "Give rating" as UC5
  usecase "Make a bid" as UC6

Buyer --> UC1
UC1 <-- Seller
Buyer --> UC2
UC2 <-- Seller 
Buyer --> UC3
UC4 <-- Seller
Buyer --> UC5
Buyer --> UC6
}

@enduml